Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      ArtifactRelation:
        linux:
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
        windows:
          ArtifactId: ${Artifact.Artifact_2.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_2.ArtifactVersion}
      SupplierTemplateConfigs:
        - Name: 新建ECS实例
          Url: ros_templates/template1.yaml
          PredefinedParameters:
            - Name: 热卖：最多支持8个玩家
              Parameters:
                PayType: PrePaid
                EcsInstanceType: ecs.e-c1m4.xlarge
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 100
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 10
              OrderList:
                - PayType
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
              Type: Normal
              Description: 性能强劲不卡顿，入门尝鲜更尽兴
            - Name: 力荐：最多支持20个玩家
              Parameters:
                PayType: PrePaid
                EcsInstanceType:
                  - ecs.e-c1m4.2xlarge
                SystemDiskCategory: cloud_essd_entry
                SystemDiskSize: 100
                InternetChargeType: PayByBandwidth
                InternetMaxBandwidthOut: 10
              OrderList:
                - PayType
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
              Type: Normal
              Description: 全天在线不卡顿，多人开黑更尽兴
            - Name: 自定义套餐
              Parameters: {}
              OrderList:
                - PayType
                - EcsInstanceType
                - SystemDiskCategory
                - SystemDiskSize
                - InternetChargeType
                - InternetMaxBandwidthOut
              Type: Custom
          AllowedRegions:
            - cn-shanghai
            - cn-hangzhou
            - cn-heyuan
            - cn-shenzhen
            - cn-wulanchabu
            - cn-huhehaote
            - cn-qingdao
            - cn-guangzhou
            - cn-fuzhou
            - cn-wuhan-lr
            - cn-nanjing
            - cn-beijing
        - Name: 选择ECS实例
          Url: ros_templates/template2.yaml
          PredefinedParameters: []
          AllowedRegions:
            - cn-shanghai
            - cn-hangzhou
            - cn-heyuan
            - cn-shenzhen
            - cn-wulanchabu
            - cn-huhehaote
            - cn-qingdao
            - cn-guangzhou
            - cn-beijing
            - cn-nanjing
            - cn-fuzhou
            - cn-wuhan-lr
    TemplateConfigs:
      - Name: 新建ECS实例
        Url: ros_templates/template1.yaml
        AllowedRegions:
          - cn-shanghai
          - cn-hangzhou
          - cn-heyuan
          - cn-shenzhen
          - cn-wulanchabu
          - cn-huhehaote
          - cn-qingdao
          - cn-guangzhou
          - cn-fuzhou
          - cn-wuhan-lr
          - cn-nanjing
          - cn-beijing
        PredefinedParameters:
          - Name: 热卖：最多支持8个玩家
            Parameters:
              PayType: PrePaid
              EcsInstanceType: ecs.e-c1m4.xlarge
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 100
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 10
            OrderList:
              - PayType
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
            Type: Normal
            Description: 性能强劲不卡顿，入门尝鲜更尽兴
          - Name: 力荐：最多支持20个玩家
            Parameters:
              PayType: PrePaid
              EcsInstanceType:
                - ecs.e-c1m4.2xlarge
              SystemDiskCategory: cloud_essd_entry
              SystemDiskSize: 100
              InternetChargeType: PayByBandwidth
              InternetMaxBandwidthOut: 10
            OrderList:
              - PayType
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
            Type: Normal
            Description: 全天在线不卡顿，多人开黑更尽兴
          - Name: 自定义套餐
            Parameters: {}
            OrderList:
              - PayType
              - EcsInstanceType
              - SystemDiskCategory
              - SystemDiskSize
              - InternetChargeType
              - InternetMaxBandwidthOut
            Type: Custom
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
      - Name: 选择ECS实例
        Url: ros_templates/template2.yaml
        AllowedRegions:
          - cn-shanghai
          - cn-hangzhou
          - cn-heyuan
          - cn-shenzhen
          - cn-wulanchabu
          - cn-huhehaote
          - cn-qingdao
          - cn-guangzhou
          - cn-beijing
          - cn-nanjing
          - cn-fuzhou
          - cn-wuhan-lr
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: palworld-
      UseDefaultValue: false
    ModifyParametersConfig:
      - TemplateName: 新建ECS实例
        Operation:
          - Name: 修改游戏参数
            Description: 修改游戏参数，请确保ECS实例处于运行中状态。
            Type: Custom
            SupportPredefinedParameters: false
            Parameters:
              - Difficulty
              - DayTimeSpeedRate
              - NightTimeSpeedRate
              - ExpRate
              - PalCaptureRate
              - PalSpawnNumRate
              - PalDamageRateAttack
              - PalDamageRateDefense
              - PlayerDamageRateAttack
              - PlayerDamageRateDefense
              - PlayerStomachDecreaceRate
              - PlayerStaminaDecreaceRate
              - PlayerAutoHPRegeneRate
              - PlayerAutoHpRegeneRateInSleep
              - PalStomachDecreaceRate
              - PalStaminaDecreaceRate
              - PalAutoHPRegeneRate
              - PalAutoHpRegeneRateInSleep
              - BuildObjectDamageRate
              - BuildObjectDeteriorationDamageRate
              - CollectionDropRate
              - CollectionObjectHpRate
              - CollectionObjectRespawnSpeedRate
              - EnemyDropItemRate
              - DeathPenalty
              - GuildPlayerMaxNum
              - PalEggDefaultHatchingTime
              - ServerPlayerMaxNum
              - ServerName
              - ServerDescription
              - AdminPassword
              - RCONEnabled
              - ServerPassword
              - AutoResetGuildTimeNoOnlinePlayers
              - BaseCampMaxNum
              - BaseCampWorkerMaxNum
              - CoopPlayerMaxNum
              - DropItemMaxNum
              - DropItemAliveMaxHours
              - DropItemMaxNum_UNKO
              - WorkSpeedRate
              - bActiveUNKO
              - bAutoResetGuildNoOnlinePlayers
              - bCanPickupOtherGuildDeathPenaltyDrop
              - bEnableAimAssistPad
              - bEnableDefenseOtherGuildPlayer
              - bEnableFastTravel
              - bEnableFriendlyFire
              - bEnableInvaderEnemy
              - bEnableNonLoginPenalty
              - bEnablePlayerToPlayerDamage
              - bExistPlayerAfterLogout
              - bIsMultiplay
              - bIsPvP
              - bIsStartLocationSelectByMap
              - BaseCampMaxNumInGuild
              - SupplyDropSpan
              - ItemWeightRate
              - bPalLost
              - bAllowGlobalPalboxImport
              - bAllowGlobalPalboxExport
            EnableLogging: false
    PrometheusConfigMap:
      新建ECS实例:
        EnablePrometheus: false
      选择ECS实例:
        EnablePrometheus: false
    SupportBackup: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo_zh-CN.png
      Locale: zh-CN
      Name: 幻兽帕鲁 - 快速部署
      ShortDescription: 幻兽帕鲁是Pocketpair开发的一款开放世界生存制作游戏，游戏于2024年1月18日发行抢先体验版本。游戏中，玩家可以在广阔的世界中收集神奇的生物“帕鲁”，派他们进行战斗、建造、做农活，工业生产等。
    - Agreements: []
      Image: resources/icons/service_logo_en-US.png
      Locale: en-US
      Name: PalWorld-Rapid Deployment
      ShortDescription: Phantom Beast Palu is an open world survival production game developed by Pocketpair. The game will be released on January 18, 2024. In the game, players can
        collect magical creatures "Palu" in the vast world and send them to fight, build, do farm work, industrial production, etc.
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: EcsImage
    ArtifactName: palwin0125
    Description: Pal_Linux_250512
    ArtifactProperty:
      ImageId: m-7xv0b16talt5x6hy86y9
      RegionId: cn-guangzhou
    SupportRegionIds:
      - cn-qingdao
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-nanjing
      - cn-shenzhen
      - cn-heyuan
      - cn-guangzhou
      - cn-fuzhou
      - cn-wuhan-lr
      - cn-chengdu
      - cn-hongkong
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-6
      - ap-southeast-5
      - ap-southeast-7
      - us-east-1
      - us-west-1
      - eu-west-1
      - me-east-1
      - eu-central-1
  Artifact_2:
    ArtifactType: EcsImage
    ArtifactName: palwinwin0125
    Description: Pal_Windows_250512
    ArtifactProperty:
      ImageId: m-7xveqzwjv5jl36cijhxh
      RegionId: cn-guangzhou
    SupportRegionIds:
      - cn-qingdao
      - cn-beijing
      - cn-zhangjiakou
      - cn-huhehaote
      - cn-wulanchabu
      - cn-hangzhou
      - cn-shanghai
      - cn-nanjing
      - cn-shenzhen
      - cn-heyuan
      - cn-guangzhou
      - cn-fuzhou
      - cn-wuhan-lr
      - cn-chengdu
      - cn-hongkong
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-1
      - ap-southeast-3
      - ap-southeast-6
      - ap-southeast-5
      - ap-southeast-7
      - us-east-1
      - us-west-1
      - eu-west-1
      - me-east-1
      - eu-central-1
